# markdownlint configuration for InferaDB Management
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Disable line length - not practical for technical docs with code, tables, URLs
MD013: false

# Allow duplicate headings in different sections (common in API docs: Request/Response)
MD024:
  siblings_only: true

# Allow emphasis as pseudo-headings for inline section labels
MD036: false

# Require language on fenced code blocks
MD040: true

# Table formatting - disable strict alignment (prettier handles this)
MD058: false
MD060: false

# Allow inline HTML when needed
MD033: false

# Allow trailing punctuation in headings (e.g., "What is IPL?")
MD026: false

# Allow multiple blank lines (sometimes useful for visual separation)
MD012: false

# Allow hard tabs in code blocks
MD010:
  code_blocks: false
